CREATE DATABASE INTERNETBANKING

------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE T_IB_ENDERECO(
	ID_ENDERECO			INT					NOT NULL			PRIMARY KEY CLUSTERED,
	DS_LOGRADOURO		VARCHAR(10)			NOT NULL,
	NR_NUMERO			NUMERIC(5)			NOT NULL,
	DS_COMPLEMENTO		VARCHAR(30)			NOT NULL,
	DS_BAIRRO			VARCHAR(20)			NOT NULL,
	DS_CIDADE			VARCHAR(30)			NOT NULL,
	DS_SIGLA_ESTADO		CHAR(2)				NOT NULL,
	DS_CEP				VARCHAR(8)			NOT NULL,
	DS_FLAG_STATUS		CHAR(1)	DEFAULT(1)	NOT NULL
);


-------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE T_IB_INFOS_FAMILIARES(
	ID_INFOS_FAMILIARES		INT					NOT NULL			PRIMARY KEY,
	NM_NOME_MAE				VARCHAR(20)			NOT NULL,
	NM_SOBRENOME_MAE		VARCHAR(30)			NOT NULL,
	NM_NOME_PAI				VARCHAR(20)			NULL,
	NM_SOBRENOME_PAI		VARCHAR(30)			NULL
);


-------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE T_IB_CONTATO(
	ID_CONTATO				INT						NOT NULL				PRIMARY KEY,
	DS_EMAIL				VARCHAR(30)				NOT NULL				UNIQUE,
	DS_TEL_RESID			VARCHAR(12)				NULL,
	DS_TEL_CEL				VARCHAR(13)				NULL,
	DS_PROPRIETARIO			VARCHAR(50)				NOT NULL				UNIQUE,
	DS_FLAG_STATUS			CHAR(1)	DEFAULT(1)		NOT NULL
);


-------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE T_IB_CLIENTE(
	ID_CLIENTE				INT					NOT NULL			PRIMARY KEY CLUSTERED,
	NR_CPF					VARCHAR(11)			NOT NULL			UNIQUE,
	DS_RG					VARCHAR(9)			NOT NULL,	
	DS_ORGAO_EMISSOR		VARCHAR(5)			NOT NULL,
	DT_NASCIMENTO			DATE				NOT NULL,
	NM_NOME					VARCHAR(20)			NOT NULL,
	NM_SOBRENOME			VARCHAR(30)			NOT NULL,
	DS_NACIONALIDADE		VARCHAR(20)			NOT NULL,
	DS_NATURALIDADE			VARCHAR(20)			NOT NULL,
	FK_ENDERECO				INT					NOT NULL,
	FK_INFOS_FAMILIARES		INT					NOT NULL,
	FK_CONTATO				INT					NOT NULL
 );

ALTER TABLE T_IB_CLIENTE ADD CONSTRAINT ID_FK_ENDERECO FOREIGN KEY (FK_ENDERECO) REFERENCES T_IB_ENDERECO(ID_ENDERECO);
ALTER TABLE T_IB_CLIENTE ADD CONSTRAINT ID_FK_INFOS_FAMILIARES FOREIGN KEY (FK_INFOS_FAMILIARES) REFERENCES T_IB_INFOS_FAMILIARES(ID_INFOS_FAMILIARES);
ALTER TABLE T_IB_CLIENTE ADD CONSTRAINT ID_FK_CONTATO FOREIGN KEY (FK_CONTATO) REFERENCES T_IB_CONTATO(ID_CONTATO);


------------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE T_IB_HIST_INFOS_ALTERADAS(
	ID_INFOS_ALTERADAS			INT						NOT NULL			PRIMARY KEY CLUSTERED,
	DS_SENHA					VARCHAR(6)				NULL,
	DT_ALTERACAO				DATE					NULL,
	DS_FLAG_ATIVO				CHAR(1)	DEFAULT(1)		NOT NULL
);

CREATE TABLE T_IB_CONTA(
	ID_CONTA					INT						IDENTITY(1, 1)			PRIMARY KEY CLUSTERED,
	FK_CLIENTE					INT						NOT NULL,
	FK_TRANSACAO				INT,
	DS_NUM_CONTA				INT						NOT NULL,		
	FK_NUM_AGENCIA				INT						NOT NULL,
	DS_SENHA_TRANSACOES			VARCHAR(4)				NOT NULL,
	DS_SENHA_LOGIN				VARCHAR(6)				NOT NULL,
	FK_HIST_INFOS_ALTERADAS		INT						NOT NULL,
	DT_CRIACAO					DATE					NOT NULL,
	DS_FLAG_ATIVO				CHAR(1)	DEFAULT(1)		NOT NULL
);

ALTER TABLE T_IB_CONTA ADD CONSTRAINT ID_FK_HIST_INFOS_ALTERADAS FOREIGN KEY (FK_HIST_INFOS_ALTERADAS) REFERENCES T_IB_HIST_INFOS_ALTERADAS(ID_INFOS_ALTERADAS);

CREATE TABLE T_IB_AGENCIA(
	ID_AGENCIA			INT			NOT NULL			PRIMARY KEY CLUSTERED,
	NUM_AGENCIA			INT			NOT NULL
);

ALTER TABLE T_IB_CONTA ADD CONSTRAINT ID_FK_NUM_AGENCIA FOREIGN KEY (FK_NUM_AGENCIA) REFERENCES T_IB_AGENCIA(ID_AGENCIA);

CREATE TABLE T_IB_BANCO(
	ID_BANCO				INT					PRIMARY KEY,
	FK_CONTAS				INT					IDENTITY(1, 1) UNIQUE,
	FK_AGENCIA				INT					NOT NULL,
	NM_FANTASIA				VARCHAR(30)			NOT NULL,
	DS_CNPJ					VARCHAR(14)			NOT NULL,
	ID_ENDERECO				INT					NOT NULL,
	DS_ISPB					VARCHAR(8)			NOT NULL
);

ALTER TABLE T_IB_BANCO ADD CONSTRAINT ID_FK_AGENCIA FOREIGN KEY (FK_AGENCIA) REFERENCES T_IB_AGENCIA(ID_AGENCIA);

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE T_IB_DEPOSITO(
	ID_DEPOSITO				INT		PRIMARY KEY,
	DATA_DEPOSITO			DATE	NOT NULL,
	CONTA_DESTINO			INT		NOT NULL,
	VALOR					NUMERIC NOT NULL
);

CREATE TABLE T_IB_SAQUE(
	ID_SAQUE				INT		PRIMARY KEY,
	DATA_SAQUE				DATE	NOT NULL,
	CONTA_ORIGEM			INT		NOT NULL,
	VALOR					NUMERIC NOT NULL
);

CREATE TABLE T_IB_TRANSFERENCIA(
	ID_TRANSFERENCIA		INT		PRIMARY KEY,
	DATA_TRANSFERENCIA		DATE	NOT NULL,	
	CONTA_ORIGEM			INT		NOT NULL,
	CONTA_DESTINO			INT		NOT NULL,
	VALOR					NUMERIC NOT NULL
);

CREATE TABLE T_IB_TRANSACOES(
	ID_TRANSACOES		INT					IDENTITY(1, 1)			PRIMARY KEY CLUSTERED,
	FK_SAQUE			INT,
	FK_DEPOSITO			INT,
	FK_TRANSFERENCIA	INT
);

ALTER TABLE T_IB_TRANSACOES ADD CONSTRAINT ID_FK_SAQUE FOREIGN KEY (FK_SAQUE) REFERENCES T_IB_SAQUE(ID_SAQUE);
ALTER TABLE T_IB_TRANSACOES ADD CONSTRAINT ID_FK_DEPOSITO FOREIGN KEY (FK_DEPOSITO) REFERENCES T_IB_DEPOSITO(ID_DEPOSITO);
ALTER TABLE T_IB_TRANSACOES ADD CONSTRAINT ID_FK_TRANSFERENCIA FOREIGN KEY (FK_TRANSFERENCIA) REFERENCES T_IB_TRANSFERENCIA(ID_TRANSFERENCIA);


ALTER TABLE T_IB_CONTA ADD CONSTRAINT ID_FK_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES T_IB_CLIENTE(ID_CLIENTE);
ALTER TABLE T_IB_CONTA ADD CONSTRAINT ID_FK_TRANSACAO FOREIGN KEY (FK_TRANSACAO) REFERENCES T_IB_TRANSACOES(ID_TRANSACOES);
